### ISSUE TITLE
Melhorar template da pagina 404

### ISSUE THREAD

**Issue by LuwkasLima** [redelivre/coletivo#11]
Precisamos melhorar o template da pagina 404 no Tema para que ela seja mais instrutiva, flexivel e em Portugues do Brasil

**Comment by everaldomatias** [comment]
Em conversa com @willowmagrini e @LuwkasLima pensamos em adicionar opções no Customizer para a pessoa personalizar as informações da página 404.

Sugestões para o que podemos dar como opções?

Minha proposta seria um **campo de texto aberto**, poderia ser até mesmo o WYSIWYG para pessoa poder usar imagens e também a opção de **listar os últimos posts dos CPTs** que a pessoa estiver usando.

**Comment by LuwkasLima** [comment]
@everaldomatias deixa isso simples:

Campo de texto com TITULO e CORPO com possibilidade de subir uma imagem e um link/botao pra ir pra HOME.

O mais aberto e flexivel possivel pros diferentes tipos de sites.

Pronto! Manda Brasa...

**Comment by diegorojas** [comment]
@everaldomatias quando você começou o papo de funcionalidade, me lembrei na hora desse papo aqui, dá uma olhada.... Acho que aqui seria um primeiro lugar para testar uma funcionalidade que não estaria no customizer talvez? 

Ou essa discussão é mais longa? Teve uma opção que o Matheus criou uma vez para a visualização do Blog em lista ou em grade que ta no Customizer hoje em dia e eu acho que se não dá para ver pelo customizer, num deve estar ĺá... Por isso talvez começar a usar a página de dashboard que o tema tem, quem sabe criar uma aba nova.. Ou será que dá para pensar num forma de tudo ser pre visualizavel e ficar no customizer? Seria o mais usabilidoido creio eu.

**Comment by LuwkasLima** [comment]
Sinceramente, nao acho que precisamos tomar tanto tempo discutindo a pagina 404. Eu sinto que ja temos opcoes, so precisa ir pra cima disso. A unica coisa que eu sempre digo eh que precisa ser o mais flexivel possivel, porque permite o uso em diferentes cenarios...

**Comment by diegorojas** [comment]
Pessoal, estamos dando uma retomada no projeto e estou revendo algumas issues aqui. Criamos um board e vamos caminhar com o desenvolvimento do Tema, para deixar ele cada vez melhor e pronto para uma eventual publicação no repositório oficial.

Me digam se a 404 como está agora atende aos pedidos dessa issue aqui e me ajudem a decidir se posso fechar ela por favor: http://coletivowp.com.br/404

**Comment by diegorojas** [comment]
Pessoal? Alguém para dar uma opinião aqui?
