### ISSUE TITLE
Blog - Autor das Postagens

### ISSUE THREAD

**Issue by LuwkasLima** [redelivre/coletivo#27]
Galera, precisamos colocar pra aparecer o perfil do Autor dos posts no blog.

Minha sugestão é apresentar o nome com a data da postagem no inicio do artigo e ao final apresentamos o avatar do autor junto com a descrição que esta no "Equipe".

**Comment by diegorojas** [comment]
Opa, pelo que vi aqui num tá de vacilo mesmo, vou colocar o link para o author ao lado da data de postagem por hora. O resumo com o avatar abaixo do post é opção do jetpack se não me engano.

**Comment by diegorojas** [comment]
Algum dev pode dar uma olhada na função coletivo_posted_on() ?
https://github.com/redelivre/tema-coletivo/blob/master/inc/template-tags.php#L92

Têm alguma coisa nela que não consegui resolver para exibir o nome linkado para o autor. A função ta lá, só num ta funcionando. Ai para num ficar um "Por" perdido que ta um display:none na class .byline 
https://github.com/redelivre/tema-coletivo/blob/master/style.css#L1412

**Comment by leobaiano** [comment]
@diegorojas o nome do autor não está sendo exibido e o ID do autor no link é sempre igual a zero porque as funções `[get_the_author()](https://codex.wordpress.org/Function_Reference/get_the_author)` e `[get_the_author_meta()](https://developer.wordpress.org/reference/functions/get_the_author_meta/)` devem ser utilizadas dentro do loop.

A forma mais limpa que consegui pensar para resolver este problema é utilizando `the_post()` e `rewind_posts()`, vou enviar um pull request com a solução.

**Comment by diegorojas** [comment]
Fala @leobaiano! Que bom ver você por aqui! Tá perfeito, obrigado por esclarecer! Testando e aprovando o PR aqui.
