### ISSUE TITLE
Descobrir onde a sessão "fantasma" está sendo gerada

### ISSUE THREAD

**Issue by everaldomatias** [redelivre/coletivo#30]
@diegorojas por favor descreva aqui mais detalhes sobre essa issue.

**Comment by LuwkasLima** [comment]
@diegorojas @everaldomatias fiz uma instalacao nova e nao consegui descobrir que sessao eh essa? Podem me indicar no print abaixo?

![page](https://user-images.githubusercontent.com/5949986/40521706-9cc31626-5f92-11e8-94de-ddd8ca93b4a3.png)

Seria essa que esta colada com o rodape escrito em BRANCO "Mantenha Atualizado"?

![screen shot 2018-05-24 at 8 42 13 pm](https://user-images.githubusercontent.com/5949986/40521798-06135938-5f93-11e8-8b8d-d0ab8773f94f.png)

**Comment by LuwkasLima** [comment]
![screen shot 2018-05-28 at 6 28 57 pm](https://user-images.githubusercontent.com/5949986/40631833-df92f7a8-62a5-11e8-9e52-776188624acb.png)

**Comment by LuwkasLima** [comment]
Bom galera, ta ai os detalhes do que encontrei e os arquivos. Acredito que os arquivos de traducao que tao sobrescrevendo a area de social...

Link: https://github.com/redelivre/tema-coletivo/search?q=follow-heading&type=Code

![screen shot 2018-05-28 at 7 17 08 pm](https://user-images.githubusercontent.com/5949986/40632368-d74d59e8-62ab-11e8-8108-dba29b87f4a2.png)

**Comment by rodineicosta** [comment]
Depois de escovar bits no código do Tema, percebi que há algumas pequenas correções a realizar, que com o tempo envio PRs. Porém, sobre a "seção fantasma" pude observar que o erro não ocorre apenas na exibição da seção "Redes Sociais", pois apenas duas seções são ocultas na configuração inicial do Tema. No entanto, várias delas não aparecem quando eu instalo. Será necessário verificar o motivo das seções que devem ser exibidas estarem ocultas e da "Rede Social" aparecer. A única correção que sugiro para essa seção seria remover a cor para que o título seja exibido conforme padrão do Tema e a seção não pareça "fantasma".

**Comment by diegorojas** [comment]
Manos, eu to tentando achar, mas ainda não, quase certeza que é um js que cria o template padrão... só não entendi qual é, alguém? O erro provavelmente acontece pq inicialmente a seção social fazia parte do footer do site e num dava para escolher a ordem dela... ai quando transformei em seção para ordenar reaproveitando as divs e classes de css, ficou alguma estruturação desse template inicial, chamando as divs dela.
